# Generated by Django 3.1.1 on 2020-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('image', models.ImageField(default='images/14.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=25)),
                ('story', models.TextField()),
                ('image', models.ImageField(default='images/7.jpg', upload_to='images/')),
            ],
        ),
    ]
