# Generated by Django 3.1.1 on 2020-09-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newevent',
            name='image',
        ),
    ]
