# Generated by Django 3.1.1 on 2020-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_field',
            field=models.ImageField(default='images/v1.jpg', upload_to='images/profile/'),
        ),
    ]
