# Generated by Django 3.1.1 on 2020-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_field',
            field=models.ImageField(default=False, upload_to='images/profile/'),
        ),
    ]
